import { Product, Order } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    slug: 'gulabi-organza-anarkali-set',
    name: 'Gulabi Organza Twirl Anarkali Set',
    tagline: 'Delicate dusty rose hand-printed organza with soft mulmul lining',
    description: 'Designed for effortless festive twirls. Crafted in lightweight dusty rose floral organza with delicate scalloped gota patti borders. Completely lined with breathable, hypoallergenic 100% mulmul cotton to ensure zero irritation on sensitive skin during long celebrations.',
    gender: 'Girls',
    styleCategory: 'Indian',
    occasions: ['Festive', 'Wedding', 'Celebration', 'Birthday'],
    price: 1490,
    mrp: 1890,
    featured: true,
    isNewArrival: true,
    isFestiveEdit: true,
    images: [
      '/images/hero_twirl_organza.jpg',
      '/images/festive_celebration_banner.jpg',
    ],
    variants: [
      { size: '20', sku: 'JS-GUL-20', stock: 8, price: 1490, mrp: 1890, chestCm: 52, waistCm: 48, lengthCm: 60 },
      { size: '22', sku: 'JS-GUL-22', stock: 12, price: 1490, mrp: 1890, chestCm: 56, waistCm: 52, lengthCm: 68 },
      { size: '24', sku: 'JS-GUL-24', stock: 10, price: 1490, mrp: 1890, chestCm: 61, waistCm: 56, lengthCm: 76 },
      { size: '26', sku: 'JS-GUL-26', stock: 6, price: 1590, mrp: 1990, chestCm: 66, waistCm: 60, lengthCm: 84 },
      { size: '28', sku: 'JS-GUL-28', stock: 4, price: 1690, mrp: 2090, chestCm: 71, waistCm: 64, lengthCm: 92 },
      { size: '30', sku: 'JS-GUL-30', stock: 3, price: 1790, mrp: 2190, chestCm: 76, waistCm: 68, lengthCm: 100 },
    ],
    modelFit: {
      modelName: 'Arya',
      heightCm: 128,
      wearingSize: '26',
      fitNote: 'Arya is 128 cm tall with a slender build. Size 26 offers an ankle-grazing festive length with room for twirling.',
    },
    details: {
      fabric: 'Fine Pure Cotton Organza with Hand-block floral motifs',
      lining: '100% Ultra-soft Mulmul Cotton, breathable & non-itchy',
      stretch: 'Non-stretch',
      softnessScore: 5,
      pockets: '1 Concealed deep right pocket for treats & trinkets',
      closure: 'Concealed YKK back zipper with padded fabric guard',
      setIncludes: '1 Anarkali Kurta, 1 Churidar / Pants, 1 Lightweight Dupatta with tasselled borders',
      careInstructions: [
        'Gentle hand wash in cold water or dry clean',
        'Use mild detergent',
        'Dry in shade to preserve pastel brilliance',
        'Warm iron on reverse side'
      ],
    },
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    slug: 'pistachio-linen-nehru-jacket-set',
    name: 'Pistachio Linen Bundi & Kurta Set',
    tagline: 'Handloom linen-blend bundi jacket with organic ivory cotton kurta pyjama',
    description: 'A sharp yet supremely comfortable ethnic ensemble. Features a tailored pistachio green linen bundi jacket accented with mother-of-pearl buttons, paired over a breathable pure cotton kurta and comfort-elasticated pyjama.',
    gender: 'Boys',
    styleCategory: 'Indo-western',
    occasions: ['Festive', 'Wedding', 'Celebration', 'Party'],
    price: 1390,
    mrp: 1750,
    featured: true,
    isNewArrival: true,
    isFestiveEdit: true,
    images: [
      '/images/hero_bundi_boy.jpg',
      '/images/festive_celebration_banner.jpg',
    ],
    variants: [
      { size: '20', sku: 'JS-PST-20', stock: 5, price: 1290, mrp: 1650, chestCm: 52, waistCm: 48, lengthCm: 44 },
      { size: '22', sku: 'JS-PST-22', stock: 9, price: 1390, mrp: 1750, chestCm: 56, waistCm: 52, lengthCm: 48 },
      { size: '24', sku: 'JS-PST-24', stock: 11, price: 1390, mrp: 1750, chestCm: 61, waistCm: 56, lengthCm: 54 },
      { size: '26', sku: 'JS-PST-26', stock: 8, price: 1390, mrp: 1750, chestCm: 66, waistCm: 60, lengthCm: 60 },
      { size: '28', sku: 'JS-PST-28', stock: 4, price: 1490, mrp: 1850, chestCm: 71, waistCm: 64, lengthCm: 66 },
      { size: '30', sku: 'JS-PST-30', stock: 3, price: 1590, mrp: 1950, chestCm: 76, waistCm: 68, lengthCm: 72 },
    ],
    modelFit: {
      modelName: 'Kabir',
      heightCm: 110,
      wearingSize: '24',
      fitNote: 'Kabir is 110 cm tall, wearing our Size 24 for comfortable movement during active celebrations.',
    },
    details: {
      fabric: '60% Natural Slub Linen, 40% Organic Cotton',
      lining: 'Soft mulmul lining on jacket, zero scratching inside',
      stretch: 'Non-stretch',
      softnessScore: 5,
      pockets: '1 Functional chest welt pocket with mini pocket square',
      closure: 'Handcrafted fabric loop buttons + soft elastic waist pyjama',
      setIncludes: '1 Bundi / Nehru Jacket, 1 Kurta, 1 Cotton Pyjama Pant',
      careInstructions: [
        'Machine wash cold on gentle cycle or hand wash',
        'Do not bleach',
        'Steam iron on medium heat'
      ],
    },
    createdAt: '2026-09-02T10:00:00Z',
  },
  {
    id: 'prod-3',
    slug: 'powder-blue-smocked-cotton-dress',
    name: 'Powder Blue Heritage Smocked Dress',
    tagline: 'Hand-smocked Peter Pan collar dress in whisper-soft woven cotton',
    description: 'Timeless vintage boutique charm meets contemporary playfulness. Hand-smocked across the bodice with pastel flora embroidery, crafted in feather-light woven cotton with gentle puff sleeves and a back sash bow.',
    gender: 'Girls',
    styleCategory: 'Western',
    occasions: ['Birthday', 'Everyday', 'Party', 'Seasonal'],
    price: 1190,
    mrp: 1490,
    featured: true,
    isNewArrival: false,
    isFestiveEdit: false,
    images: [
      '/images/hero_smock_girl.jpg',
    ],
    variants: [
      { size: '18', sku: 'JS-PBD-18', stock: 6, price: 1090, mrp: 1390, chestCm: 46, waistCm: 46, lengthCm: 46 },
      { size: '20', sku: 'JS-PBD-20', stock: 8, price: 1190, mrp: 1490, chestCm: 51, waistCm: 50, lengthCm: 52 },
      { size: '22', sku: 'JS-PBD-22', stock: 10, price: 1190, mrp: 1490, chestCm: 56, waistCm: 54, lengthCm: 58 },
      { size: '24', sku: 'JS-PBD-24', stock: 7, price: 1290, mrp: 1590, chestCm: 61, waistCm: 58, lengthCm: 66 },
      { size: '26', sku: 'JS-PBD-26', stock: 5, price: 1290, mrp: 1590, chestCm: 66, waistCm: 62, lengthCm: 72 },
    ],
    modelFit: {
      modelName: 'Meera',
      heightCm: 98,
      wearingSize: '20',
      fitNote: 'Meera is 98 cm tall, wearing Size 20. Flared A-line silhouette provides airy comfort in humid weather.',
    },
    details: {
      fabric: '100% Fine Long-staple Combed Cotton',
      lining: 'Self-cotton lined bodice and skirt',
      stretch: 'Gentle Stretch',
      softnessScore: 5,
      pockets: 'Side slip pocket',
      closure: 'Mother-of-pearl buttons with matching back tie-up sash',
      setIncludes: '1 Hand-smocked Cotton Dress + Matching hair bow clip',
      careInstructions: [
        'Gentle hand or machine wash inside out',
        'Do not wring roughly',
        'Cool iron avoided on smocking embroidery'
      ],
    },
    createdAt: '2026-09-03T10:00:00Z',
  },
  {
    id: 'prod-4',
    slug: 'saffron-marigold-angrakha-dhoti-set',
    name: 'Saffron Angrakha Dhoti Set',
    tagline: 'Warm terracotta-marigold cotton angrakha with contrast piping',
    description: 'Traditional grace reimagined for modern children. The wrap-around angrakha style eliminates tricky over-the-head dressing, paired with ready-to-wear comfort dhoti pants tailored with soft anti-roll waistband.',
    gender: 'Boys',
    styleCategory: 'Indian',
    occasions: ['Festive', 'Celebration', 'Wedding'],
    price: 990,
    mrp: 1290,
    featured: true,
    isNewArrival: true,
    isFestiveEdit: true,
    images: [
      '/images/saffron_angrakha_toddler.jpg',
    ],
    variants: [
      { size: '16', sku: 'JS-ANG-16', stock: 6, price: 890, mrp: 1190, chestCm: 42, waistCm: 40, lengthCm: 32 },
      { size: '18', sku: 'JS-ANG-18', stock: 8, price: 990, mrp: 1290, chestCm: 46, waistCm: 44, lengthCm: 36 },
      { size: '20', sku: 'JS-ANG-20', stock: 12, price: 990, mrp: 1290, chestCm: 51, waistCm: 48, lengthCm: 42 },
      { size: '22', sku: 'JS-ANG-22', stock: 5, price: 1090, mrp: 1390, chestCm: 56, waistCm: 52, lengthCm: 48 },
    ],
    modelFit: {
      modelName: 'Vihaan',
      heightCm: 84,
      wearingSize: '18',
      fitNote: 'Vihaan is 84 cm tall. Size 18 with wrap-around tie-ups allows easy adjustability.',
    },
    details: {
      fabric: '100% Breathable Organic Khadi Cotton',
      lining: 'Unlined single-layer featherweight cotton for ultimate breathability',
      stretch: 'Non-stretch',
      softnessScore: 5,
      pockets: 'None',
      closure: 'Soft cotton fabric tie strings (No harsh metal snaps or zippers)',
      setIncludes: '1 Angrakha Kurta Top, 1 Pre-stitched Cotton Dhoti',
      careInstructions: [
        'Hand wash separately in cold water',
        'Mild detergent only',
        'Flat dry in shade'
      ],
    },
    createdAt: '2026-09-04T10:00:00Z',
  },
  {
    id: 'prod-5',
    slug: 'ivory-botanical-co-ord-set',
    name: 'Ivory Botanical Camp Shirt & Shorts Set',
    tagline: 'Breezy tailored resort co-ord in hand-screened tropical botanical print',
    description: 'Effortless holiday styling for boys and girls alike. Relaxed camp collar shirt with wooden coconut buttons and matching tailored pull-on shorts with deep pockets for beach treasures and everyday adventures.',
    gender: 'Unisex',
    styleCategory: 'Western',
    occasions: ['Everyday', 'Party', 'Seasonal', 'Birthday'],
    price: 890,
    mrp: 1190,
    featured: false,
    isNewArrival: true,
    isFestiveEdit: false,
    images: [
      '/images/botanical_resort_coord.jpg',
    ],
    variants: [
      { size: '22', sku: 'JS-BOT-22', stock: 10, price: 890, mrp: 1190, chestCm: 56, waistCm: 52, lengthCm: 42 },
      { size: '24', sku: 'JS-BOT-24', stock: 14, price: 890, mrp: 1190, chestCm: 61, waistCm: 56, lengthCm: 46 },
      { size: '26', sku: 'JS-BOT-26', stock: 8, price: 990, mrp: 1290, chestCm: 66, waistCm: 60, lengthCm: 50 },
      { size: '28', sku: 'JS-BOT-28', stock: 5, price: 1090, mrp: 1390, chestCm: 71, waistCm: 63, lengthCm: 54 },
      { size: '30', sku: 'JS-BOT-30', stock: 4, price: 1190, mrp: 1490, chestCm: 76, waistCm: 66, lengthCm: 58 },
      { size: '32', sku: 'JS-BOT-32', stock: 4, price: 1290, mrp: 1590, chestCm: 81, waistCm: 70, lengthCm: 62 },
    ],
    modelFit: {
      modelName: 'Reyansh',
      heightCm: 122,
      wearingSize: '26',
      fitNote: 'Reyansh is 122 cm tall with an active build. Relaxed boxy Size 26 silhouette allows free movement.',
    },
    details: {
      fabric: '70% Cotton, 30% Linen with enzyme wash for softness',
      lining: 'Unlined for breezy summer cooling',
      stretch: 'Non-stretch',
      softnessScore: 4,
      pockets: '2 Deep side trouser pockets + 1 chest pocket',
      closure: 'Natural coconut shell buttons + drawstring elastic waistband',
      setIncludes: '1 Resort Collar Shirt, 1 Tailored Bermuda Shorts',
      careInstructions: [
        'Machine wash cold with like colours',
        'Tumble dry low or line dry',
        'Warm iron if desired'
      ],
    },
    createdAt: '2026-09-05T10:00:00Z',
  },
  {
    id: 'prod-6',
    slug: 'dusty-mint-peplum-sharara-set',
    name: 'Dusty Mint Peplum Sharara Set',
    tagline: 'Modern Indo-western peplum top with tiered flare sharara pants',
    description: 'A contemporary silhouette blending Indian festive artistry with modern movement. The short peplum kurta is accented with subtle mirror-work lace along the neckline, paired with a flared tiered sharara designed specifically to avoid tripping while running.',
    gender: 'Girls',
    styleCategory: 'Indo-western',
    occasions: ['Festive', 'Wedding', 'Party', 'Celebration'],
    price: 1590,
    mrp: 1990,
    featured: true,
    isNewArrival: false,
    isFestiveEdit: true,
    images: [
      '/images/mint_peplum_sharara.jpg',
    ],
    variants: [
      { size: '22', sku: 'JS-SHR-22', stock: 4, price: 1490, mrp: 1890, chestCm: 56, waistCm: 52, lengthCm: 40 },
      { size: '24', sku: 'JS-SHR-24', stock: 8, price: 1590, mrp: 1990, chestCm: 61, waistCm: 56, lengthCm: 44 },
      { size: '26', sku: 'JS-SHR-26', stock: 9, price: 1590, mrp: 1990, chestCm: 66, waistCm: 59, lengthCm: 48 },
      { size: '28', sku: 'JS-SHR-28', stock: 5, price: 1690, mrp: 2090, chestCm: 71, waistCm: 62, lengthCm: 52 },
      { size: '30', sku: 'JS-SHR-30', stock: 4, price: 1790, mrp: 2190, chestCm: 76, waistCm: 65, lengthCm: 56 },
      { size: '32', sku: 'JS-SHR-32', stock: 3, price: 1890, mrp: 2290, chestCm: 81, waistCm: 68, lengthCm: 60 },
      { size: '34', sku: 'JS-SHR-34', stock: 2, price: 1990, mrp: 2390, chestCm: 86, waistCm: 72, lengthCm: 64 },
    ],
    modelFit: {
      modelName: 'Zara',
      heightCm: 116,
      wearingSize: '24',
      fitNote: 'Zara is 116 cm tall, wearing Size 24. Fitted chest with twirling flare waistline.',
    },
    details: {
      fabric: 'Fine Viscose Chanderi with Cotton Lining',
      lining: '100% Breathable Mulmul throughout top and sharara',
      stretch: 'Non-stretch',
      softnessScore: 5,
      pockets: 'Hidden pocket inside sharara flare',
      closure: 'Back keyhole button + soft elasticated waist sharara',
      setIncludes: '1 Peplum Kurti, 1 Tiered Sharara Pant, 1 Chiffon Dupatta with pom-pom edges',
      careInstructions: [
        'Dry clean recommended for first wash',
        'Subsequent washes: gentle hand wash cold',
        'Do not iron directly over mirror accents'
      ],
    },
    createdAt: '2026-09-06T10:00:00Z',
  },
  {
    id: 'prod-7',
    slug: 'blush-terracotta-tiered-tulle-frock',
    name: 'Blush & Ochre Layered Birthday Frock',
    tagline: 'Soft tiered micro-tulle with hypoallergenic cotton inner slip',
    description: 'The quintessential celebration dress designed without any itchiness. Multiple layers of cloud-soft micro-tulle atop a 100% organic cotton underslip, finished with satin-bound armholes and a removable pearl-accented belt.',
    gender: 'Girls',
    styleCategory: 'Western',
    occasions: ['Birthday', 'Party', 'Celebration'],
    price: 1390,
    mrp: 1790,
    featured: true,
    isNewArrival: true,
    isFestiveEdit: false,
    images: [
      '/images/birthday_tulle_frock.jpg',
    ],
    variants: [
      { size: '18', sku: 'JS-BLF-18', stock: 7, price: 1290, mrp: 1690, chestCm: 46, waistCm: 44, lengthCm: 50 },
      { size: '20', sku: 'JS-BLF-20', stock: 12, price: 1390, mrp: 1790, chestCm: 51, waistCm: 48, lengthCm: 58 },
      { size: '22', sku: 'JS-BLF-22', stock: 9, price: 1390, mrp: 1790, chestCm: 56, waistCm: 52, lengthCm: 66 },
      { size: '24', sku: 'JS-BLF-24', stock: 6, price: 1490, mrp: 1890, chestCm: 61, waistCm: 56, lengthCm: 74 },
      { size: '26', sku: 'JS-BLF-26', stock: 4, price: 1490, mrp: 1890, chestCm: 66, waistCm: 60, lengthCm: 82 },
    ],
    modelFit: {
      modelName: 'Sia',
      heightCm: 102,
      wearingSize: '22',
      fitNote: 'Sia is 102 cm tall, wearing Size 22. Fluffy tiered tulle creates maximum birthday twirl with zero scratch.',
    },
    details: {
      fabric: 'Ultra-fine soft nylon tulle over cotton satin',
      lining: 'Dual layer 100% combed cotton slip',
      stretch: 'Comfort Stretch',
      softnessScore: 5,
      pockets: 'None',
      closure: 'Concealed zipper with protective under-placket',
      setIncludes: '1 Tiered Tulle Party Frock + 1 Matching floral headband',
      careInstructions: [
        'Gentle hand wash inside out in cold water',
        'Do not machine tumble',
        'Hang to air fluff, steam lightly'
      ],
    },
    createdAt: '2026-09-07T10:00:00Z',
  },
  {
    id: 'prod-8',
    slug: 'mustard-indigo-cotton-kurta-pyjama',
    name: 'Mustard Marigold Classic Boy Kurta Set',
    tagline: 'Pure breathable woven cotton kurta with wooden buttons and churidar pyjama',
    description: 'An understated classic for festive mornings, family pujas, and celebration gatherings. Made from breathable hand-spun cotton yarn in a rich marigold ochre shade with ivory tailored collar detailing.',
    gender: 'Boys',
    styleCategory: 'Indian',
    occasions: ['Festive', 'Everyday', 'Celebration'],
    price: 790,
    mrp: 990,
    featured: false,
    isNewArrival: false,
    isFestiveEdit: true,
    images: [
      '/images/festive_celebration_banner.jpg',
      '/images/hero_bundi_boy.jpg',
    ],
    variants: [
      { size: '28', sku: 'JS-MST-28', stock: 15, price: 790, mrp: 990, chestCm: 71, waistCm: 64, lengthCm: 68 },
      { size: '30', sku: 'JS-MST-30', stock: 18, price: 790, mrp: 990, chestCm: 76, waistCm: 68, lengthCm: 76 },
      { size: '32', sku: 'JS-MST-32', stock: 10, price: 890, mrp: 1090, chestCm: 81, waistCm: 72, lengthCm: 84 },
      { size: '34', sku: 'JS-MST-34', stock: 8, price: 890, mrp: 1090, chestCm: 86, waistCm: 76, lengthCm: 90 },
      { size: '36', sku: 'JS-MST-36', stock: 6, price: 990, mrp: 1190, chestCm: 91, waistCm: 80, lengthCm: 96 },
      { size: '38', sku: 'JS-MST-38', stock: 5, price: 1090, mrp: 1290, chestCm: 96, waistCm: 84, lengthCm: 102 },
      { size: '40', sku: 'JS-MST-40', stock: 4, price: 1190, mrp: 1390, chestCm: 102, waistCm: 88, lengthCm: 108 },
    ],
    modelFit: {
      modelName: 'Dev',
      heightCm: 146,
      wearingSize: '34',
      fitNote: 'Dev is 146 cm tall with an athletic build, wearing our Size 34 with relaxed comfort ease.',
    },
    details: {
      fabric: '100% Handspun Pre-shrunk Pure Cotton',
      lining: 'Unlined for maximum warm-weather coolness',
      stretch: 'Non-stretch',
      softnessScore: 5,
      pockets: '2 Deep functional side kurta pockets',
      closure: 'Hand-carved wooden buttons on front placket + elasticated drawstring pyjama',
      setIncludes: '1 Long Kurta, 1 Cotton Comfort Pyjama',
      careInstructions: [
        'Machine wash cold on standard cycle',
        'Wash dark colors separately first 2 times',
        'Medium hot iron'
      ],
    },
    createdAt: '2026-09-08T10:00:00Z',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'JS-2026-101',
    source: 'WhatsApp',
    customer: {
      name: 'Pooja Sharma',
      phone: '+91 99855 31519',
      email: 'pooja.sharma@gmail.com',
      address: 'Flat 402, Lotus Towers, Indiranagar',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560038',
      childHeightCm: 126,
      childChestInches: 26,
      specialNotes: 'For Arya’s upcoming cousin wedding on Sunday. Please pack gently!',
    },
    items: [
      {
        productId: 'prod-1',
        productName: 'Gulabi Organza Twirl Anarkali Set',
        productImage: 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=400&q=80',
        size: '26',
        sku: 'JS-GUL-26',
        quantity: 1,
        unitPrice: 1590,
        totalPrice: 1590,
      }
    ],
    subtotal: 1590,
    discount: 0,
    shippingFee: 0,
    grandTotal: 1590,
    orderStatus: 'Packed',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    awbNumber: 'DTDC8829104',
    courierPartner: 'DTDC Express',
    createdAt: '2026-09-20T14:30:00Z',
    updatedAt: '2026-09-21T11:00:00Z',
  },
  {
    id: 'ord-102',
    orderNumber: 'JS-2026-102',
    source: 'WhatsApp',
    customer: {
      name: 'Rohan Mehra',
      phone: '+91 98234 56789',
      email: 'rohan.mehra@outlook.com',
      address: 'B-12, Sector 44, Near Golf Course',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201303',
      childHeightCm: 108,
      childChestInches: 24,
      specialNotes: 'Need gift wrapping with personalized handwritten note: Happy Birthday Kabir!',
    },
    items: [
      {
        productId: 'prod-2',
        productName: 'Pistachio Linen Bundi & Kurta Set',
        productImage: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=400&q=80',
        size: '24',
        sku: 'JS-PST-24',
        quantity: 1,
        unitPrice: 1390,
        totalPrice: 1390,
      }
    ],
    subtotal: 1390,
    discount: 100,
    shippingFee: 0,
    grandTotal: 1290,
    orderStatus: 'Confirmed',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    createdAt: '2026-09-22T09:15:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'ord-103',
    orderNumber: 'JS-2026-103',
    source: 'WhatsApp',
    customer: {
      name: 'Ananya Deshmukh',
      phone: '+91 97654 32109',
      email: 'ananya.d@yahoo.com',
      address: '701, Sea Breeze Apartments, Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
      childHeightCm: 96,
      childChestInches: 22,
      specialNotes: 'Chatted on WhatsApp regarding sizing. Opted for Size 22.',
    },
    items: [
      {
        productId: 'prod-3',
        productName: 'Powder Blue Heritage Smocked Dress',
        productImage: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=400&q=80',
        size: '22',
        sku: 'JS-PBD-22',
        quantity: 1,
        unitPrice: 1190,
        totalPrice: 1190,
      },
      {
        productId: 'prod-7',
        productName: 'Blush & Ochre Layered Birthday Frock',
        productImage: 'https://images.unsplash.com/photo-1596870230751-ebdfce98ec42?auto=format&fit=crop&w=400&q=80',
        size: '22',
        sku: 'JS-BLF-22',
        quantity: 1,
        unitPrice: 1390,
        totalPrice: 1390,
      }
    ],
    subtotal: 2580,
    discount: 200,
    shippingFee: 0,
    grandTotal: 2380,
    orderStatus: 'Dispatched',
    paymentStatus: 'Paid',
    paymentMethod: 'UPI',
    awbNumber: 'BLUEDART665421',
    courierPartner: 'BlueDart Air',
    createdAt: '2026-09-21T18:20:00Z',
    updatedAt: '2026-09-22T14:40:00Z',
  }
];
